services:
  soap-service-container:
    image: soap-service
    build:
      context: soap-service
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file: ./soap-service/.env.docker
    depends_on:
      wallet_db_container:
        condition: service_healthy
        restart: true
  wallet_db_container:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: wallet_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
